name: Windows
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually trigger build of Idris 2.'
        required: true
env:
  MSYSTEM: MINGW64
  MSYS2_PATH_TYPE: inherit
  SCHEME: scheme
  CC: gcc
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Init
        run: |
          git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Idris 2
        run: git clone --depth 1 https://github.com/idris-lang/Idris2
      - name: Get Chez Scheme
        run: |
          git clone --depth 1 https://github.com/cisco/ChezScheme
          c:\msys64\usr\bin\bash -l -c "pacman -S --noconfirm tar make zip"
          echo "::set-env name=PWD::$(c:\msys64\usr\bin\cygpath -u $(pwd))"
      - name: Configure and Build Chez Scheme
        run: |
          c:\msys64\usr\bin\bash -l -c "cd $env:PWD && cd ChezScheme && ./configure --threads && make"
      - name: Set Path
        run: |
          $chez="$(pwd)\ChezScheme\ta6nt\bin\ta6nt"
          $idris="$(pwd)\Idris2\.idris2"
          $output="$(pwd)\output"
          echo "::add-path::$chez"
          echo "::add-path::$idris\bin"
          echo "::set-env name=IDRIS_PREFIX::$idris"
          echo "::set-env name=PREFIX::$(c:\msys64\usr\bin\cygpath -u $idris)"
      - name: Test Scheme
        run: |
          scheme --version
      - name: Bootstrap and install
        run: c:\msys64\usr\bin\bash -l -c "cd $env:PWD/Idris2 && make bootstrap && make install"
      - name: Prepare the data to compression
        run: |
          New-Item -ItemType directory -Name output/idris2-windows-nightly/chez
          New-Item -ItemType directory -Name output/idris2-windows-nightly/idris2
          Move-Item -Path configure.ps1 -Destination output/idris2-windows-nightly
          Move-Item -Path ChezScheme/ta6nt/bin output/idris2-windows-nightly/chez
          Move-Item -Path ChezScheme/ta6nt/boot output/idris2-windows-nightly/chez
          Move-Item -Path Idris2/.idris2 output/idris2-windows-nightly/idris2
          Move-Item -Path Idris2/bootstrap output/idris2-windows-nightly/idris2
          Compress-Archive -Path output/idris2-windows-nightly -DestinationPath output/idris2-windows-nightly.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/idris2-windows-nightly.zip
          asset_name: idris2-windows-nightly.zip
          asset_content_type: application/zip
